version: '3.8'

services:
  app:
    build: .
    container_name: chatbot-app
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: chatbot-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
